name: Build Documentation

on:
  push:
    branches: [ develop ]
    paths: [ 'docs/**' ]
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        python-version: [ "3.9" ]

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout GitHub Pages
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -e '.[docs]'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build HTML with Sphinx
        run: |
          cd docs
          make html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
